name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: "v"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: HBOICTKeuzewijzer.Api/Dockerfile
          push: true
          tags: |
            dragmoria/hboictkeuzewijzerapi:latest
            dragmoria/hboictkeuzewijzerapi:${{ steps.version.outputs.full }}